### ISSUE TITLE
Improving the UI

### ISSUE THREAD

**Issue by ayushsgit** [srbmaury/To-dos-list#1]
Hey I am planning to make this UI better like adjusting Title so it looks more user friendly and also tweak the Buttons and textbox so they look better

**Comment by ayushsgit** [comment]
https://dancing-kleicha-c6ceac.netlify.app/
hey I deployed the changes in this site , If you like them i will do the pull request

**Comment by srbmaury** [comment]
> https://dancing-kleicha-c6ceac.netlify.app/ hey I deployed the changes in this site , If you like them i will do the pull request

That's beautiful.
You may raise a PR
Can it be responsive for phones too?

**Comment by ayushsgit** [comment]
You need to enable Desktop Mode in order for it to function in phone. Normally it does not work

**Comment by asharma991** [comment]
Can I make it responsive?

**Comment by asharma991** [comment]
Can we close this now? @srbmaury

**Comment by srbmaury** [comment]
Yes
