### ISSUE TITLE
Making the Readme of this Project look better for Users

### ISSUE THREAD

**Issue by ayushsgit** [srbmaury/To-dos-list#3]
I can add pictures of the project and The To-Do Lists functionalities so people visiting this repo can see and understand easily

**Comment by ayushsgit** [comment]
Hey i have changed the ReadMe
https://github.com/ayushsgit/To-dos-list/blob/master/README.md
If you liked it i can do a PR

**Comment by srbmaury** [comment]
Yes you may do.
